### ISSUE TITLE
AimTux Update??

### ISSUE THREAD

**Issue by LWSS** [daniel-Jones/matrixdisplay#1]
This is cool, but waiting for AimTUX for CS2??

**Comment by daniel-Jones** [comment]
Kisak-Strike 2 when????

**Comment by LWSS** [comment]
> Kisak-Strike 2 when????

https://github.com/SwagSoftware/Kisak-thug

sneak preview 👀

**Comment by daniel-Jones** [comment]
NOTICE ME SENPAI
